### ISSUE TITLE
Big Data

### ISSUE THREAD

**Issue by outlineutils** [Esper89/unicode-analyze#1]
Hi all,

I was on our very important daily internal conference call with the CEO and he announced that the next big thing is going to be something called Big Data. It sounds incredibly impressive! Is this something we can incorporate into our unicode analysis software solution? Maybe as a backend service running on the Docker and the Sequel Services? Have a think about it! Also, if you could pop an estimate of how long it would take on my desk first thing Monday morning that would be great!

Happy Tuesday and have a great week! 😃 😃 😃 ❤️ ❤️ ❤️

Janet | Accounts

**Comment by Esper89** [comment]
For ‘big data’, see [`src/unicode.rs`](https://github.com/Esper89/unicode-analyze/blob/master/src/unicode.rs).
